### ISSUE TITLE
Postdanmark plugin trows js error

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5302] opened 2020-04-15 18:40 UTC
Postdanmark plugin optional pickup point throw this js error in checkout:

This site overrides Array.from() with an implementation that doesn't support iterables, which could cause Google Maps JavaScript API v3 to not work correctly.

RS 3.0.1

**Comment by anhredweb** [comment] 2020-04-16 02:27
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by VanTrieuThanh** [comment] 2020-04-16 06:25
I have reproduced this issue but I'm not having your trouble. So can you give me more information. Tks @Rmh1978

**Comment by Rmh1978** [comment] 2020-04-17 11:03
I don´t have any trouble with the functions but the js error is there.

Try it here : www.mydomain.dk/tmp/testsite215clean/checkout

**Comment by NguyenBao10** [comment] 2020-06-23 07:22
Hi @Rmh1978 , it does not affect to any function, so it's not a major problem now.
We will fix in REDSHOP-5974 and let you know later.

**Comment by ducredweb** [comment] 2021-01-26 05:12
The error saying "Array.from()"  is due to Mootools js library as it interferes the core js of Array.prototype, this is fixed on the new versions of Mootools, this is not redshop-related issue.

**Closed by ducredweb** 2021-01-26 05:12 UTC
Labels: Backlog, REDSHOP-5974
