### ISSUE TITLE
Redshop Product Content Replacement Plugin >> Class 'productHelper' not found

### ISSUE THREAD

**Issue by Rmh1978** [redCOMPONENT-COM/redSHOP#5308] opened 2020-04-15 22:11 UTC
When the plugin is enabled it breaks the site with this error:
0 - Class 'productHelper' not found

Redshop Product Content Replacement Plugin v 2.0.0
RS 3.0.1

**Comment by anhredweb** [comment] 2020-04-16 02:30
Hi @Rmh1978 , 
We're going to verify your report soon.
Thanks for your sharing.
redSHOP team.

**Comment by VanTrieuThanh** [comment] 2020-04-16 09:01
It good for me. Can you give me some information for bug reproduce? @Rmh1978 
![Screenshot from 2020-04-16 16-00-45](https://user-images.githubusercontent.com/44457418/79436746-784c3300-7ffb-11ea-892c-58718fc78dcb.png)

**Comment by Rmh1978** [comment] 2020-04-16 09:31
Hi @VanTrieuThanh 

You can see it on my RS 3.0.1 testsite here   www.mydomain.dk/tmp/testsite215clean/
@NguyenBao10 has credentials.

I have made a copy of the module i use for the P contents view. Its in the right side colum. Now the Content plugin not published, so it output {redshop:3531}. When i enable the plugin it breaks.

**Comment by VanTrieuThanh** [comment] 2020-04-22 04:32
Hi @Rmh1978 
I see out put {redshop:3531}, but I don't see error when I enable the plugin on my local.
I have see error on your site. Dev will verify it

**Comment by anhredweb** [comment] 2020-04-22 04:33
Hi @Rmh1978 ,

We couldn't verified the error you mentioned, may be it is specify your site issue, not because of redSHOP origin. @NguyenBao10 could you please help to check.

Thanks,
H.A

**Comment by Rmh1978** [comment] 2020-04-22 11:12
@anhredweb 
Perhaps.

I could also see that the db lookup for the Product content template in the plugin settings don´t work. I changed it to a plain text box so it shows my template id but it still fails. So there is something more in the code that is not up to date.

I am running php 7.3.17 on my site maybe that causes conflicts. But i just downgraded to php 5.6.40 still with error.

**Comment by Rmh1978** [comment] 2020-04-22 11:13
@anhredweb
Could you send me the content plugin zip that you are using to test.

**Comment by hoang-tran-redweb** [comment] 2020-05-13 04:55
@Rmh1978 
I fixed on the test your site. Please uninstall plugin content redshop product old, and install plugin new.

**Comment by Rmh1978** [comment] 2020-05-13 08:31
Hi @hoang-tran-redweb & @anhredweb 

I see it works. Thank you :-)

I am running 2.1.2.1 live and will not go live with a newer version before you release a more stable version than 3.0.1
So i will download it when i go live.

**Comment by hoang-tran-redweb** [comment] 2020-05-13 08:38
@Rmh1978 Ok. Please change status issue help me.

**Comment by Rmh1978** [comment] 2020-07-17 11:28
Hi @hoang-tran-redweb 

Can you publish the "Redshop Product Content Replacement Plugin" on Redcomponent.
It is not in the download section.

**Comment by NguyenBao10** [comment] 2020-07-29 07:45
i did, we unpublished it to improve some things @Rmh1978

**Closed** 2020-10-15 03:34 UTC
Labels: Issue Resolved
